name: Build and Distribute iOS - dev

on:
  # push:
  #   branches:
  #     - develop
  workflow_dispatch:

jobs:
  build-ios:
    name: Build and Distribute ipa
    runs-on: macos-latest
    env:
      APPLE_APP_STORE_CONNECT_API_KEY_BASE64: ${{ secrets.APPLE_APP_STORE_CONNECT_API_KEY_BASE64 }}
      APPLE_APP_STORE_CONNECT_API_KEY_ISSUER_ID: ${{ secrets.APPLE_APP_STORE_CONNECT_API_KEY_ISSUER_ID }}
      APPLE_APP_STORE_CONNECT_API_KEY_KEY_ID: ${{ secrets.APPLE_APP_STORE_CONNECT_API_KEY_KEY_ID }}

      APPLE_BUILD_CERTIFICATE_BASE64: ${{ secrets.APPLE_BUILD_CERTIFICATE_BASE64 }}
      APPLE_BUILD_CERTIFICATE_P12_PASSWORD: ${{ secrets.APPLE_BUILD_CERTIFICATE_P12_PASSWORD }}

      APPLE_DISTRIBUTION_CERTIFICATE_BASE64: ${{ secrets.APPLE_DISTRIBUTION_CERTIFICATE_BASE64 }}
      APPLE_DISTRIBUTION_CERTIFICATE_P12_PASSWORD: ${{ secrets.APPLE_DISTRIBUTION_CERTIFICATE_P12_PASSWORD }}

      APPLE_MOBILEPROVISION_BASE64_UAT: ${{ secrets.APPLE_MOBILEPROVISION_BASE64_UAT }}

      APPLE_KEYCHAIN_PASSWORD: ${{ secrets.APPLE_KEYCHAIN_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install the Apple certificate and provisioning profile
        run: |
          BUILD_CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          DISTRIBUTION_CERTIFICATE_PATH=$RUNNER_TEMP/distribution_certificate.p12
          PP_PATH=$RUNNER_TEMP/temp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          echo -n "$APPLE_BUILD_CERTIFICATE_BASE64" | base64 --decode --output $BUILD_CERTIFICATE_PATH
          echo -n "$APPLE_DISTRIBUTION_CERTIFICATE_BASE64" | base64 --decode --output $DISTRIBUTION_CERTIFICATE_PATH

          security create-keychain -p "$APPLE_KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$APPLE_KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          security import $BUILD_CERTIFICATE_PATH -P "$APPLE_BUILD_CERTIFICATE_P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security import $DISTRIBUTION_CERTIFICATE_PATH -P "$APPLE_DISTRIBUTION_CERTIFICATE_P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH
          security find-identity -v

          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          echo -n "$APPLE_MOBILEPROVISION_BASE64_UAT" | base64 --decode --output $PP_PATH
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Set up Flutter
        uses: flutter-actions/setup-flutter@v3
        with:
          channel: stable
          version: 3.35.7

      - name: Install dependencies
        run: flutter pub get

      - name: Run build_runner
        run: |
          flutter pub run build_runner build --delete-conflicting-outputs

      - name: Build ipa
        run: |
          flutter build ipa --flavor ci-uat --dart-define-from-file .env.uat --export-options-plist=ios/ExportOptions-ci-dev.plist

      - name: Upload IPA to App Store Connect
        run: |
          mkdir -p ~/.appstoreconnect/private_keys
          echo -n "$APPLE_APP_STORE_CONNECT_API_KEY_BASE64" | base64 --decode --output ~/.appstoreconnect/private_keys/AuthKey_${APPLE_APP_STORE_CONNECT_API_KEY_KEY_ID}.p8
          xcrun altool --upload-app --type ios \
            --file build/ios/ipa/*.ipa \
            --apiKey $APPLE_APP_STORE_CONNECT_API_KEY_KEY_ID --apiIssuer $APPLE_APP_STORE_CONNECT_API_KEY_ISSUER_ID \
            --output-format xml
